language: go

go:
- '1.15'

jobs:
  include:
    - stage: all
      name: Verify
      script: make verify && git diff --exit-code
    - name: Build test adapter
      script: make build-test-adapter
    - name: Unit tests
      script: make test

